spring:
  flyway:
    locations: classpath:db.migrations
    url: jdbc:mysql://localhost:3306/itactesttask
    user: root
    password: root
  datasource:
    url: jdbc:mysql://localhost:3306/itactesttask
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
